### ISSUE TITLE
Enhance NGINX ReplicaSet Configuration for Better Practices

### ISSUE THREAD

**Issue by seatriumwbgt1** [TheToriqul/k8s-replicaset#1]
#### Description:
The current `ReplicaSet` configuration for managing NGINX web server pods works effectively but can be improved for better maintainability, robustness, and scalability. The following enhancements are suggested to align with Kubernetes best practices and production standards:

---

#### Current State:
1. Uses `nginx:latest` image, which may lead to unexpected updates and instability.
2. Lacks resource `requests` and `limits`, potentially causing resource contention.
3. No health checks (`livenessProbe` or `readinessProbe`), which are essential for ensuring traffic routes to healthy pods.
4. Does not specify a namespace, deploying resources to the default namespace.
5. Minimal metadata (annotations and labels) for documentation and filtering.
6. Comments can be refined for clarity and brevity.

---

#### Proposed Improvements:
1. Use a specific NGINX image version (e.g., `nginx:1.25.2`) instead of `latest` for stability.
2. Add resource `requests` and `limits`:
   - **Requests:** Memory: `64Mi`, CPU: `250m`
   - **Limits:** Memory: `128Mi`, CPU: `500m`
3. Add health checks:
   - **Liveness Probe:** HTTP GET `/` on port `80` with a 5s initial delay.
   - **Readiness Probe:** HTTP GET `/` on port `80` with a 5s initial delay.
4. Specify a namespace for logical resource separation (e.g., `web-namespace`).
5. Add annotations for better documentation and traceability.
6. Add labels (e.g., `tier: frontend`) to improve resource management.
7. Update comments for better clarity.

---

#### Acceptance Criteria:
- [ ] Update the `ReplicaSet` YAML to include all proposed improvements.
- [ ] Ensure that the updated configuration passes validation with `kubectl apply -f`.
- [ ] Verify the pods behave as expected with the new configurations (e.g., health probes working, resources properly allocated).

---

#### References:
- [Kubernetes ReplicaSet Documentation](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/)
- [Best Practices for Resource Management in Kubernetes](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/)
- [Probes in Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)

#### Additional Context:
This enhancement is aimed at improving the scalability and maintainability of the `ReplicaSet` configuration for production readiness.

**Comment by TheToriqul** [comment]
Done
